### ISSUE TITLE
[FEATREQ] Auto populate the data from nusmods timetable

### ISSUE THREAD

**Issue by benclmnt** [frizensami/nus-timetable-optimizer#28]
**Is your feature request related to a problem? Please describe.**
As a user, I want to import timetable from nusmods

**Describe the solution you'd like**
- Copy the generated link from nusmods timetable
- nus-timetable optimizer can auto populate the modules (without me manually entering it in)

Do you think this is a good idea?

**Comment by frizensami** [comment]
Yes, sounds like a great idea actually! That also seems like the more common use-case.

**Comment by frizensami** [comment]
If this is something you'd like to do and file a PR for, please feel free.
